version: "3.9"
services:
  zammad:
    image: zammad/zammad:6
    container_name: zammad
    restart: always
    ports:
      - "8080:8080"
    environment:
      - NGINX_SERVER_SCHEME=http
      - NGINX_SERVER_PORT=8080
      - RAILS_LOG_TO_STDOUT=true
      - ZAMMAD_RAILS4=true
    volumes:
      - zammad-data:/opt/zammad
volumes:
  zammad-data:

