version: "3.9"
services:
  NEXTCLOUD_NAME:
    image: nextcloud:28-apache
    container_name: nc-NEXTCLOUD_NAME
    restart: always
    ports:
      - "NEXTCLOUD_PORT:80"
    environment:
      - NEXTCLOUD_ADMIN_USER=NEXTCLOUD_ADMIN
      - NEXTCLOUD_ADMIN_PASSWORD=NEXTCLOUD_PASSWORD
      - PHP_MEMORY_LIMIT=512M
      - POST_MAX_SIZE=2G
      - UPLOAD_MAX_FILESIZE=2G
    volumes:
      - nextcloud_NEXTCLOUD_NAME:/var/www/html
volumes:
  nextcloud_NEXTCLOUD_NAME:





